server:
  port: 8080
kite:
  snow-flake:
    center-id: 1
    machine-id: 1
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/kite?characterEncoding=utf-8}
    username: root
    password: root
#mybatis:
#  mapper-locations: classpath*:mapper/*Mapper.xml
#  configuration:
#    map-underscore-to-camel-case: true
logging:
  level:
    com.oktfolio.kite.mapper: debug
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
      db-config:
        id-type: auto